/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItassistPipelineRouteImport } from './routes/itassist.pipeline'
import { Route as ItassistErrorsRouteImport } from './routes/itassist.errors'
import { Route as ItassistDashboardRouteImport } from './routes/itassist.dashboard'

const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItassistPipelineRoute = ItassistPipelineRouteImport.update({
  id: '/itassist/pipeline',
  path: '/itassist/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ItassistErrorsRoute = ItassistErrorsRouteImport.update({
  id: '/itassist/errors',
  path: '/itassist/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ItassistDashboardRoute = ItassistDashboardRouteImport.update({
  id: '/itassist/dashboard',
  path: '/itassist/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/itassist/dashboard': typeof ItassistDashboardRoute
  '/itassist/errors': typeof ItassistErrorsRoute
  '/itassist/pipeline': typeof ItassistPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/itassist/dashboard': typeof ItassistDashboardRoute
  '/itassist/errors': typeof ItassistErrorsRoute
  '/itassist/pipeline': typeof ItassistPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/itassist/dashboard': typeof ItassistDashboardRoute
  '/itassist/errors': typeof ItassistErrorsRoute
  '/itassist/pipeline': typeof ItassistPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/itassist/dashboard'
    | '/itassist/errors'
    | '/itassist/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/itassist/dashboard'
    | '/itassist/errors'
    | '/itassist/pipeline'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/itassist/dashboard'
    | '/itassist/errors'
    | '/itassist/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  ItassistDashboardRoute: typeof ItassistDashboardRoute
  ItassistErrorsRoute: typeof ItassistErrorsRoute
  ItassistPipelineRoute: typeof ItassistPipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itassist/pipeline': {
      id: '/itassist/pipeline'
      path: '/itassist/pipeline'
      fullPath: '/itassist/pipeline'
      preLoaderRoute: typeof ItassistPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itassist/errors': {
      id: '/itassist/errors'
      path: '/itassist/errors'
      fullPath: '/itassist/errors'
      preLoaderRoute: typeof ItassistErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itassist/dashboard': {
      id: '/itassist/dashboard'
      path: '/itassist/dashboard'
      fullPath: '/itassist/dashboard'
      preLoaderRoute: typeof ItassistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  ItassistDashboardRoute: ItassistDashboardRoute,
  ItassistErrorsRoute: ItassistErrorsRoute,
  ItassistPipelineRoute: ItassistPipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
